name: subsnap
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+9

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Database & Auth
  supabase_flutter: ^2.3.4
  uuid: ^4.5.1


  # Icons & UI
  google_fonts: ^8.0.1
  font_awesome_flutter: ^10.6.0
  flex_color_scheme: ^8.4.0
  fl_chart: ^1.1.1

  # Payments & RevenueCat
  purchases_flutter: ^9.11.0

  # Notifications
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0

  # Utilities
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  google_sign_in: ^7.2.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.4
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.7.1


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true


